#app
server:
    port: 8080

#spring
spring:
  devtools:
    restart:
      enabled: true

  # PG DATABASE CONFIG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:/db/schema-pg.sql
#    data: classpath:/db/data-pg.sql
    url: jdbc:postgresql://localhost:5432/jkgl
    username: postgres
    password: 123456
    platform: pg
    initialization-mode: always
    continue-on-error: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jkgl.*.entity
  typeEnumsPackage: com.jkgl.common
#  typeEnumsPackage: com.jkgl.*.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: POSTGRE_SQL
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

